### ISSUE TITLE
Dispatcher gets called twice ?

### ISSUE THREAD

**Issue by littlejavachild** [square/flow#171] opened 2016-03-02 16:49 UTC
I have a chat application that requires the user to be logged in. I save this as a boolean in `SharedPreferences`. And the key (values from an `enum`) to `Flow` depends on whether the user is logged in or not.  

``` java
@Override
protected void attachBaseContext(Context baseContext) {
    // Initialize PrefUtils
    PrefUtils.init(baseContext);

    // Default key depends upon whether the user is logged in or not
    // If user is logged in, default key is Screens.CHAT
    // If the user is not logged in, default key is Screens.WELCOME
    boolean isLoggedIn = PrefUtils.getBoolean(PrefUtils.Key.IS_USER_LOGGED_IN,false);
    key = isLoggedIn ? Screens.CHAT : Screens.WELCOME;

    // Configure Flow
    baseContext = Flow.configure(baseContext, this)
            .dispatcher(new ViewDispatcher(this))
            .defaultKey(key)
            .install();
    super.attachBaseContext(baseContext);
}
```

and my `Dispatcher` looks like this:  

``` java
@Override
public void dispatch(Traversal traversal, TraversalCallback callback) {
    Object dest = traversal.destination.top();
    Object source = traversal.origin == null ? null : traversal.origin.top();

    Logger.d(TAG,"Dispatcher called");
    Logger.d(TAG, source == null ? "SOURCE: Null" : "SOURCE: " + ((Screens) source).name());
    Logger.d(TAG, "DESTINATION: " + ((Screens) dest).name());

    ViewGroup root = (ViewGroup) activity.findViewById(R.id.root);

    if (traversal.origin != null) {
        int childCount = root.getChildCount();
        // Our container has a root view with an ImageView in it.
        // If child count > 1, we need to remove the child at position = 1
        // because ImageView is at position = 0
        if (childCount > 1) {
            // save state
            traversal.getState(traversal.origin.top()).save(root.getChildAt(1));
            // remove the added views
            removeAllViewsAfter(root,0);
        }
    }

    // default layout = welcome screen
    @LayoutRes int layout;
    if(dest.equals(Screens.WELCOME)){
        layout = R.layout.view_welcome;
    }else if(dest.equals(Screens.CHAT)){
        layout = R.layout.view_chat;
    }else{
        throw new IllegalArgumentException("Unrecognized Screen");
    }

    View incomingView = LayoutInflater
            .from(traversal.createContext(dest, activity))
            .inflate(layout, root, false);
    traversal.getState( traversal.destination.top() ).restore(incomingView);
    root.addView( incomingView );
    callback.onTraversalCompleted();
}
```

but if I keep the app idle (on any screen) and view the logs, then I find that dispatcher is called twice. My log looks like this:  

```
03-02 22:02:52.463 32264-32264/chat.example.app D/ViewDispatcher: Dispatcher called
03-02 22:02:52.463 32264-32264/chat.example.app D/ViewDispatcher: SOURCE: Null
03-02 22:02:52.463 32264-32264/chat.example.app D/ViewDispatcher: DESTINATION: WELCOME
03-02 22:02:59.086 32264-32264/chat.example.app D/ViewDispatcher: Dispatcher called
03-02 22:02:59.086 32264-32264/chat.example.app D/ViewDispatcher: SOURCE: Null
03-02 22:02:59.086 32264-32264/chat.example.app D/ViewDispatcher: DESTINATION: WELCOME
```

I have no idea why this is happening. I end up with my layout being drawn twice on the chat screen. 

Why is this happening? :)

**Comment by loganj** [comment] 2016-03-02 19:53
When you say "keep the app idle", what does that mean? Are you leaving the app and returning to it? Do you see this on cold start (ie launching the app without having previously launched it)? 

What version of Android, and what's your Activity's superclass? 

Can you share a test app that demonstrates it?

**Comment by littlejavachild** [comment] 2016-03-03 08:50
@loganj  

> When you say "keep the app idle", what does that mean?  
By this I mean that I launch the app from the launcher and leave it as is - no interactions, nothing.  

> Are you leaving the app and returning to it?
I see this when I return to the app, too. When the screen goes off and comes back on, I see the layout redrawn.

> Do you see this on cold start (ie launching the app without having previously launched it)?
Yes.

> What version of Android, and what's your Activity's superclass?
I've seen this on Marshmallow and Jelly Bean (those are the only real phones I have). `AppCompatActivity`.

 > Can you share a test app that demonstrates it?
Sure, let me work on it :)

**Comment by littlejavachild** [comment] 2016-03-03 11:00
@loganj  
Here's the repo: https://github.com/littlejavachild/HelloFlow :)

I think I found what might be causing the problem here. The problem is here:  
```java
if (traversal.origin != null) {
    /**
    * This part of code is only reached when transitioning from one screen to another
    * removeViewsAfter( ) is not called when the same screen  is being displayed again
    * as a result of onRestart( ) -> onResume( ).
    * Result : some views are drawn again
    */
}
```  

This is my solution:
```java
if (traversal.origin != null) {
    /**
     * Same code as before
     */
}else{
    // remove all views to ensure that duplicate views are not added again
    removeAllViewsAfter(root,0);
}
```

**Comment by mmangliers** [comment] 2016-04-06 08:24
I have the dispatcher being called twice. I'd love to finish building this app with flow but I might have to move back to fragments and the built in back stack

**Comment by JoshKoch25** [comment] 2016-04-25 22:54
I also see this problem (returning to app, screen turns off, switch from recents, etc.)

**Comment by Zhuinden** [comment] 2016-07-02 11:43
The bootstrap traversal is initiated when the dispatcher is set in `InternalLifecycleIntegration.onResume()` even if the activity was not re-created.

**Comment by rjrjr** [comment] 2016-09-02 17:00
Could someone confirm that the fix just merged from https://github.com/square/flow/pull/190 covers this as well?

**Comment by lassem** [comment] 2017-02-03 09:46
The fact that the bootstrap traversal is initiated when the dispatcher is set in `nternalLifecycleIntegration.onResume()` as @Zhuinden points out causes problems for us. (Location permission dialog on a Google maps view goes crazy as the view is recreated after accepting)

Why is the dispatcher removed in onPause og added in onResume (thus initiating a bootstrap traversal when not we're not actually bootstrapping...)?

We're now running with the following hack. Not loving it.

```            if (direction == Direction.REPLACE && outgoingState == null && containerView.getChildCount() == 1) {
                // @hack: This is the Flow bootstrap traversal, but it has a bug that triggers it on onResume, but in this case we already have a view-hierarchy in place.
                callback.onTraversalCompleted();
                return;
            }
```

**Comment by Zhuinden** [comment] 2017-02-03 10:16
> Why is the dispatcher removed in onPause og added in onResume (thus initiating a bootstrap traversal when not we're not actually bootstrapping...)?

The problem is that it starts a bootstrap traversal in general. I took Flow's source and added that the bootstrap is not started if the `setDispatcher` is called from `onResume()` instead of `onActivityCreated()`.

**Comment by rjrjr** [comment] 2017-04-12 23:47
I think this has not been an issue for us because our containers all short circuit if asked to show something that they are already showing -- that is, if the view currently visible was built from a key equal to the one that is being dispatched, we no-op. This is similar in spirit to @lassem's workaround, but less hacky.

I don't see how it's safe to avoid bootstrapping the new dispatcher in onResume(). Your apps aren't queuing up changes to Flow while the app is paused, but others might be. If we simply don't dispatch, your display will be stale.

WRT @lassem 's question, "Why is the dispatcher removed in onPause og added in onResume," I assume @loganj did that to ensure that the app isn't needlessly rendering views in response to navigation events that happen while it's in the background.

Am I missing something?

**Comment by Zhuinden** [comment] 2017-04-13 06:49
if you put the app in background and bring it foreground, you can't short-circuit based on previous/new key because previous key is empty because it is a bootstrap traversal

**Comment by rjrjr** [comment] 2017-04-13 20:00
The previous key is not useful in this situation, and is not what I'm talking about. You're comparing the key embedded in the context of the currently visible view with the new key.

**Comment by rjrjr** [comment] 2017-04-13 20:03
This is a dup of #173, no?

**Closed by rjrjr** 2017-04-13 20:03 UTC
Labels: bug
