### ISSUE TITLE
Dispatcher doesn't know if resuming or starting fresh

### ISSUE THREAD

**Issue by hannesstruss** [square/flow#173] opened 2016-03-04 12:55 UTC
Currently, `Dispatcher.dispatch` is invoked on every `onResume` of the Activity. 

If the `onResume` does not follow an `onDestroy` and the previous view is still in place (e.g. after opening the app switcher and returning), a naive Dispatcher will recreate the view, losing its state.

Something like this happens e.g. in `flow-sample-basic`:
1. Open app
2. Type some characters
3. Open app switcher and close again
4. `KeyChanger` has created a new view and added it on top of the old one, both views are visible. The new view lost the text in the EditText.

<img src="https://cloud.githubusercontent.com/assets/115381/13527165/63a83178-e20d-11e5-97be-21198e360d4e.gif" width="100"> (Click to enlarge)

This does not occur after an orientation change, as the view is destroyed before `dispatch` is called.

Should `dispatch` always be called after `onResume`? Is it the responsibility of the `Dispatcher` (or `KeyChanger` when using `KeyDispatcher`) to detect whether an action is required or if the traversal can be ignored?

**Comment by Zhuinden** [comment] 2016-03-04 15:01
It's strange, but you are right. Even if you're on the second view (second key), then if you put the app to background and bring it back, a key change is executed:

    MainKeyChanger﹕ Change Key: [null] - [com.zhuinden.flow_alpha_project.OtherKey@52a0dba4]

I'm not sure this is expected behavior.

**Comment by adelnizamutdinov** [comment] 2016-03-14 14:10
previously when we had full control of dispatching I always omitted calls to `FlowConfig.onPause()` and `FlowConfig.onResume()`

now since everything is done implicitly through Fragments, I don't have that chance anymore

can you please consider bringing back all the explicit lifecycle method calls?

**Comment by verres630** [comment] 2016-03-16 10:16
Should InternalLifecycleIntegration onResume() method look like this?
```
@Override public void onResume() {
    super.onResume();
    if (!dispatcherSet) {
      flow.setDispatcher(dispatcher,true);
      dispatcherSet = true;
    }
  }
```
When I minimalize application and onResume is called, KeyManager is incrementing unnecessary Key object counter. This breaks services lifecycle.

**Comment by rjrjr** [comment] 2016-09-02 17:00
Could someone confirm that the fix just merged from https://github.com/square/flow/pull/190 covers this as well?

**Comment by rjrjr** [comment] 2017-04-12 23:51
This strikes me as a dup of #171, where I just argued that this behavior is by design.

**Comment by Zhuinden** [comment] 2017-04-13 06:51
Yes, but if you put the app in background and bring it foreground, you can't short-circuit based on previous/new key because previous key is empty because it is a bootstrap traversal

**Comment by rjrjr** [comment] 2017-04-13 14:41
It's not about the previous key in the transiiton. It's about the key
embedded in the view that is currently showing.

Something like `if
(traversal.destination.top().equals(Flow.getKey(containerFrame.getChildAt(0))
return;`

**Comment by Zhuinden** [comment] 2017-04-13 15:39
Ew.

**Comment by rjrjr** [comment] 2017-04-13 16:26
Seems like pretty traditional UI de-bouncing to me. Obviously that phrase
wouldn't appear literally.

**Comment by rjrjr** [comment] 2017-04-13 17:02
Controller: "Hey UI, show this."
UI: "Already am, thanks."

**Comment by rjrjr** [comment] 2017-04-13 18:23
Thinking about this some more, I don't see what else is possible. Flow cannot, should not make assumptions about what state your dispatcher is in. The problem here is in thinking of the call to dispatch as being an event. It isn't, it's a notification of the state that Flow expects you to be rendering. 

Keeping this issue open to address in Alpha 3, but as a documentation task.

**Closed** 2017-04-14 16:29 UTC
Labels: enhancement

**Comment by Saketme** [comment] 2018-03-20 06:13
FYI for others who also ran into this issue, don't forget to call `TraversalCallback#onTraversalCompleted()` when you ignore a key change otherwise the back-history will not get updated. We ran into really strange problems where further key changes were just getting ignored because of this. 

So the final code would look somewhat like this:

```java
Object existingKey = Flow.getKey(frame.getChildAt(0));
Object incomingKey = incomingState.getKey();

if (outgoingState == null && existingKey.equals(incomingKey) && direction == Direction.REPLACE) {
  // https://github.com/square/flow/issues/173
  callback.onTraversalCompleted();
  return;
}
```
